name: background_task_example
description: "Demonstrates how to use the background_task plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.12.0

dependencies:
  background_task:
    path: ../

  cupertino_icons: ^1.0.2

  dio: ^5.4.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl:

  path: ^1.9.1

  path_provider: ^2.1.2

  permission_handler: ^11.1.0

  sembast: ^3.8.9+1

  sembast_sqflite: ^2.2.2
  sqflite: ^2.4.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono:

flutter:
  uses-material-design: true
